locale: en-US
site_theme: default
title: My Academic Profile
title_separator: "-"
name: Zheng Shi
description: Zheng Shi's Academic Profile
url: https://zhengshi-econ.github.io
repository: zhengshi-econ/zhengshi-econ.github.io
author:
  avatar: profile.png
  name: Zheng Shi
  bio: Corporate Finance
  location: Wuhan China
  employer: Huazhong University Of Science And Technology
  email: zhengshiecon@163.com
  googlescholar: https://scholar.google.com/citations?user=u2hYcSAAAAAJ&hl=en
  orcid: https://orcid.org/0000-0001-9562-8850
  github: zhengshi-econ
publication_category:
  books:
    title: Books
  manuscripts:
    title: Journal Articles
  conferences:
    title: Conference Papers
breadcrumbs: false
words_per_minute: 160
future: true
read_more: disabled
talkmap_link: false
staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
    - name
    - email
    - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  hide: false
analytics:
  provider: "false"
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+
  

incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
timezone: Etc/UTC
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
